# Grafana Data Sources Configuration
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://observer-prometheus:9090
    isDefault: true
    editable: true
